[api]
# listen_addr = "*"
# port = 8080
key = "1234"

[commands.ipv4]
bgp_route = "show bgp ipv4 unicast {target}"
bgp_community = "show bgp ipv4 unicast community {target}"
bgp_aspath = "show bgp ipv4 unicast regexp {target}"
ping = "ping -4 -c 5 -I {source} {target}"
traceroute = "traceroute -4 -w 1 -q 1 -s {source} {target}"

[commands.ipv6]
bgp_route = "show bgp ipv6 unicast {target}"
bgp_community = "show bgp ipv6 unicast community {target}"
bgp_aspath = "show bgp ipv6 unicast regexp {target}"
ping = "ping -6 -c 5 -I {source} {target}"
traceroute = "traceroute -6 -w 1 -q 1 -s {source} {target}"
